version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      # update Docker
      - run: |
          docker version
          sudo service docker stop
          curl -fsSL https://get.docker.com/ | sudo sh
      - run: docker version
      - deploy:
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            git config --global user.email "vzDevelopment@github.invalid"
            git config --global user.name "vzDevelopment CI"
            git branch --set-upstream-to=origin/${CIRCLE_BRANCH} ${CIRCLE_BRANCH}
            ./release.sh
