version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: "Lint the code"
          command: |
            npm install --only dev
            ./node_modules/.bin/eslint .
      # update Docker
      - run: |
          docker version
          sudo service docker stop
          curl -fsSL https://get.docker.com/ | sudo sh
      - run: docker version
      # clean up after linting and testing e.g. remove node_modules/
      # so it isn't including in any production images
      - run:
          name: "Clean up linting and test files"
          command: |
            git clean -fxd
            git reset --hard
      - deploy:
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            git config --global user.email "vzDevelopment@github.invalid"
            git config --global user.name "vzDevelopment CI"
            git branch --set-upstream-to=origin/${CIRCLE_BRANCH} ${CIRCLE_BRANCH}
            ./release.sh
