version: 2
jobs:
  build:
    machine: true
    environment: # apparently expansion doesn't work here yet: https://discuss.circleci.com/t/environment-variable-expansion-in-working-directory/11322
      - GOPATH=/home/circleci/go
      - GOVERSION=1.8.3
      - OS=linux
      - ARCH=amd64
    steps:
      - checkout
      # lint the code
      - run: |
          npm install --only dev
          ./node_modules/.bin/eslint .
      # update Docker
      - run: |
          docker version
          sudo service docker stop
          curl -fsSL https://get.docker.com/ | sudo sh
      - run: docker version
      # - run: ./test.sh

      # clean up after linting and testing e.g. remove node_modules/
      # so test packages aren't included in any production images
      - deploy:
          name: "Clean up linting and test files"
          command: |
            git clean -fxd
            git reset --hard
      - deploy:
          name: "Build docker image and release"
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            git config --global user.email "vzDevelopment@github.invalid"
            git config --global user.name "vzDevelopment CI"
            git branch --set-upstream-to=origin/${CIRCLE_BRANCH} ${CIRCLE_BRANCH}
            ./release.sh
